# Build settings
markdown: kramdown

plugins:
- jekyll-language-plugin
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-picture-tag
- jekyll-paginate-v2

language_data: data.%%
language_includes_dir: _i18n

# for SEO
title: "Koło Studentów Informatyki UJ"
description: "Witaj na stronie najlepszego koła naukowego na świecie!"
url: "https://ksi.ii.uj.edu.pl"

social_logo: "/images/logo_for_fb.png"

social:
  links:
    - https://www.facebook.com/ksi.uj
    - https://github.com/ksiuj
    - https://instagram.com/ksiuj
google_site_verification: itaBFyu7_-vU6FYw0hKhfel6XlK3jx-daMyl4FIlQSk

picture:
  nomarkdown: false
  suppress_warnings: true

pagination:
  enabled: true
  per_page: 20
  permalink: '/:num/'
  sort_reverse: true
  title: ':title - :num'

sass:
  style: compressed
