source 'https://rubygems.org'
gem 'jekyll', '< 4.0'
gem 'jekyll-paginate-v2'
gem 'jekyll-language-plugin'
gem 'jekyll-sitemap'
gem 'jekyll-seo-tag'
gem 'kramdown-parser-gfm'
group :jekyll_plugins do
  gem 'jekyll_picture_tag', '1.4.0'
end
